#!/usr/bin/env bash
# Measures M1 (physical storage per additional usable worktree): native
# `git worktree add` vs `wt0 create --require-cow`, on a real CoW filesystem.
#
# This is the CI counterpart to the macOS/APFS numbers measured by hand in
# docs/design-partners/flam-migration.md ("After" section, gate 7): it runs
# the same kind of measurement on Linux Btrfs and Windows ReFS in
# .github/workflows/ci.yml and publishes the table to the job summary.
#
#   WT0=target/debug/wt0 VOLUME=/mnt/wt0-btrfs N=5 bash tests/measure_m1.sh
#
# Physical usage is read from the filesystem itself (`df`, or on Windows a
# PowerShell drive query), never `du`: `du` charges a CoW clone its full
# logical size even when its blocks are shared with the base, so it cannot
# see the saving this script exists to measure.
set -euo pipefail

WT0="${WT0:?set WT0 to the wt0 binary path}"
VOLUME="${VOLUME:?set VOLUME to a directory on the filesystem under test}"
N="${N:-5}"
FIXTURE_FILES="${FIXTURE_FILES:-2000}"
FIXTURE_FILE_KB="${FIXTURE_FILE_KB:-50}"
MAX_NATIVE_SHARE_PCT="${MAX_NATIVE_SHARE_PCT:-10}"

[ -x "$WT0" ] || { echo "missing wt0 binary at $WT0" >&2; exit 1; }
[ -d "$VOLUME" ] || { echo "missing volume directory $VOLUME" >&2; exit 1; }
if [ "$N" -lt 2 ]; then
  echo "N must be >= 2 (need worktree 1 and worktree N to compute a marginal cost)" >&2
  exit 1
fi

REPO="$VOLUME/measure-m1-repo"
rm -rf "$REPO" "$VOLUME"/native-* "$VOLUME"/wt0-*

# ---- physical used-bytes reader -------------------------------------------
# Linux (Btrfs): GNU `df -k --output=used`.
# Windows (ReFS): Git Bash's df goes through an MSYS translation layer we
# have not been able to verify gives physical, clone-aware numbers for a
# diskpart-created ReFS volume, so when WT0_M1_PS_DRIVE is set we ask
# PowerShell for the drive's Used bytes directly instead (see ci.yml).
# macOS (APFS, local debugging only): BSD `df -Pk`, no --output support.
used_kb() {
  local dir="$1"
  if [ -n "${WT0_M1_PS_DRIVE:-}" ]; then
    local used_bytes
    used_bytes=$(powershell.exe -NoProfile -Command "(Get-PSDrive ${WT0_M1_PS_DRIVE}).Used" | tr -d '\r')
    awk -v b="$used_bytes" 'BEGIN{printf "%d", b/1024}'
  elif df -k --output=used "$dir" >/dev/null 2>&1; then
    df -k --output=used "$dir" | tail -n1 | tr -d ' '
  else
    df -Pk "$dir" | awk 'NR==2{print $3}'
  fi
}

now_s() {
  if [ -n "${EPOCHREALTIME:-}" ]; then
    echo "$EPOCHREALTIME"
  else
    date +%s
  fi
}
elapsed_s() { awk -v a="$1" -v b="$2" 'BEGIN{printf "%.3f", a-b}'; }
kb_to_mb() { awk -v k="$1" 'BEGIN{printf "%.1f", k/1024}'; }
# Marginal physical cost per worktree beyond the first, in KiB: the first
# worktree of any base commit pays a one-time materialization, so the
# steady-state per-worktree cost is measured from worktree 1 to worktree N.
marginal_kb() { awk -v k1="$1" -v kN="$2" -v n="$3" 'BEGIN{printf "%.2f", (kN-k1)/(n-1)}'; }
pct_num() { awk -v w="$1" -v n="$2" 'BEGIN{ if (n<=0) print "nan"; else printf "%.1f", (w/n)*100 }'; }
fmt_pct() { [ "$1" = "nan" ] && echo "n/a" || echo "$1%"; }

make_repo() {
  local dir="$1" total_bytes=$((FIXTURE_FILES * FIXTURE_FILE_KB * 1024))
  mkdir -p "$dir/src"
  ( cd "$dir"
    git init -q
    git config user.email m1@wt0.dev
    git config user.name measure-m1
    # One head|split pipeline instead of FIXTURE_FILES forked `head` calls:
    # far fewer processes, which matters a lot on Windows/MSYS. Deterministic
    # *size* (exactly FIXTURE_FILE_KB per file), not deterministic bytes.
    head -c "$total_bytes" /dev/urandom | split -b "$((FIXTURE_FILE_KB * 1024))" -a 4 - src/f_
    {
      echo "# measure_m1 fixture"
      echo "$FIXTURE_FILES files x ${FIXTURE_FILE_KB}KiB, generated by tests/measure_m1.sh"
    } > README.md
    printf 'fixture\n' > NOTES.txt
    git add -A
    git commit -q -m "seed: $FIXTURE_FILES x ${FIXTURE_FILE_KB}KiB fixture" )
}

fixture_mib=$((FIXTURE_FILES * FIXTURE_FILE_KB / 1024))
echo "Building fixture repository: $FIXTURE_FILES files x ${FIXTURE_FILE_KB}KiB (~${fixture_mib} MiB) on $VOLUME"
make_repo "$REPO"

# ---- native `git worktree add` ---------------------------------------------
sync 2>/dev/null || true
native_before=$(used_kb "$VOLUME")
native_time_sum=0
native_after_1=""
i=1
while [ "$i" -le "$N" ]; do
  t0=$(now_s)
  ( cd "$REPO" && git worktree add -q -b "native/$i" "$VOLUME/native-$i" HEAD )
  t1=$(now_s)
  native_time_sum=$(awk -v a="$native_time_sum" -v b="$(elapsed_s "$t1" "$t0")" 'BEGIN{printf "%.4f", a+b}')
  if [ "$i" -eq 1 ]; then
    sync 2>/dev/null || true
    native_after_1=$(used_kb "$VOLUME")
  fi
  i=$((i + 1))
done
sync 2>/dev/null || true
native_after_n=$(used_kb "$VOLUME")

# ---- wt0 create --require-cow ----------------------------------------------
wt0_before=$(used_kb "$VOLUME")
wt0_time_sum=0
wt0_after_1=""
i=1
while [ "$i" -le "$N" ]; do
  t0=$(now_s)
  ( cd "$REPO" && "$WT0" create "bench/$i" --path "$VOLUME/wt0-$i" --require-cow >/dev/null )
  t1=$(now_s)
  wt0_time_sum=$(awk -v a="$wt0_time_sum" -v b="$(elapsed_s "$t1" "$t0")" 'BEGIN{printf "%.4f", a+b}')
  if [ "$i" -eq 1 ]; then
    sync 2>/dev/null || true
    wt0_after_1=$(used_kb "$VOLUME")
  fi
  i=$((i + 1))
done
sync 2>/dev/null || true
wt0_after_n=$(used_kb "$VOLUME")

# ---- derive figures ---------------------------------------------------------
native_total_1_kb=$((native_after_1 - native_before))
native_total_n_kb=$((native_after_n - native_before))
wt0_total_1_kb=$((wt0_after_1 - wt0_before))
wt0_total_n_kb=$((wt0_after_n - wt0_before))

native_marginal_kb=$(marginal_kb "$native_total_1_kb" "$native_total_n_kb" "$N")
wt0_marginal_kb=$(marginal_kb "$wt0_total_1_kb" "$wt0_total_n_kb" "$N")
wt0_share_pct=$(pct_num "$wt0_marginal_kb" "$native_marginal_kb")

native_mean_s=$(awk -v s="$native_time_sum" -v n="$N" 'BEGIN{printf "%.2f", s/n}')
wt0_mean_s=$(awk -v s="$wt0_time_sum" -v n="$N" 'BEGIN{printf "%.2f", s/n}')

summary=$(cat <<EOF
### Gate 7 — Measure M1 (marginal storage per worktree)

Fixture: $FIXTURE_FILES tracked files, ~${fixture_mib} MiB. Physical usage
from the filesystem itself, never \`du\`.

| Worktrees | Native Git (MiB) | wt0 (MiB) | wt0 as share of native |
| ---: | ---: | ---: | ---: |
| 1 | $(kb_to_mb "$native_total_1_kb") | $(kb_to_mb "$wt0_total_1_kb") | $(fmt_pct "$(pct_num "$wt0_total_1_kb" "$native_total_1_kb")") |
| $N | $(kb_to_mb "$native_total_n_kb") | $(kb_to_mb "$wt0_total_n_kb") | $(fmt_pct "$(pct_num "$wt0_total_n_kb" "$native_total_n_kb")") |

Marginal cost per additional worktree: native **$(kb_to_mb "$native_marginal_kb") MiB**,
wt0 **$(kb_to_mb "$wt0_marginal_kb") MiB** (wt0 is $(fmt_pct "$wt0_share_pct") of native).

Mean create time (N=$N): native ${native_mean_s}s, wt0 ${wt0_mean_s}s.
EOF
)

printf '%s\n' "$summary"
if [ -n "${GITHUB_STEP_SUMMARY:-}" ]; then
  printf '%s\n' "$summary" >> "$GITHUB_STEP_SUMMARY"
fi

if [ "$wt0_share_pct" = "nan" ]; then
  echo "FAIL: native marginal cost was <= 0 KiB ($native_marginal_kb); cannot compute a share" >&2
  exit 1
fi
under_bar=$(awk -v p="$wt0_share_pct" -v m="$MAX_NATIVE_SHARE_PCT" 'BEGIN{print (p<=m) ? 1 : 0}')
if [ "$under_bar" -ne 1 ]; then
  echo "FAIL: wt0 marginal cost is ${wt0_share_pct}% of native's (native $(kb_to_mb "$native_marginal_kb") MiB/worktree, wt0 $(kb_to_mb "$wt0_marginal_kb") MiB/worktree), exceeds the ${MAX_NATIVE_SHARE_PCT}% bar" >&2
  exit 1
fi
